JasonDsouza212/free-hit

README.md, src/DB/product.js, src/components/card.js, src/components/header.js, src/css/index.css
=> Update: added some codes, deleted

package-lock.json, package.json, src/components/card.js
Lazy loading for images using package.
Different effects can be applied like 'blur', 'opacity' and 'black-and-white'
=> Add lazy-loading for images

src/DB/product.js
=> Update invalid URLs #28

src/DB/product.js
I've added codegreeper to DB .
=> [product]: added codegreeper

src/components/card.jsx, src/css/index.css
* fixed card height
* added class name
* added visit website button
=> Fix: card height

src/DB/product.json
Changed the name of Product.JS file to Product.JSON
Removed , after every description from Product.Json file
=>  Renamed and Improved Product File

.github/dependabot.yml, .github/workflows/greetings.yml, .github/workflows/josn-check.yml, CODE_OF_CONDUCT.md, LICENSE, src/DB/product.json, src/components/card.jsx
- json file changed
- card.jsx updated
- added gh actions
solved #51 #46  #48 
- Added code_of_conduct
- Added LICENSE
=> fix: website json file problem

.gitignore, src/DB/product.json
This site helps you to download the latest American and Korean movies and shows
=> add moviesnation for free american and korean shows

src/DB/product.json, src/components/card.jsx
Added Chrome Extensions button with necessary data.
Updated the position
=> issue#60: Chrome Extensions 

src/css/index.css
Fix: #43 
Set the default cursor on card hover.
=> Set default cursor on card hover

src/DB/product.json
Updated product.json to minify product names and description for extension category.
=> Issue #60  revised :: Updated  Extension names

package.json, pnpm-lock.yaml
=> chore: removed unwanted packages

src/DB/product.json
The 'Soap2Day' product had the wrong link connected to it, this should do the job 👍
=> Correct Soap2Day's link

README.md
Added Vite Pnpm and Vercel in the Project use section.
Updated Preview Image.
=> Issue #14: Updated Readme File

src/components/footer.jsx, src/index.css
=> Enhanced footer styling 

src/DB/product.json
This website lets you create resumes, cover letter & networking messages with the help of AI.....
=> Added Wonsulting.ai

src/index.css
Added A Feature , Shadows to each container to beautify it .
before -
after -
=> feat : Added Shadow to Container (for cards)

src/DB/product.json, src/components/card.jsx
- Added separate AI section & tools
Fixed #103 
https://user-images.githubusercontent.com/88102392/229671205-20971fd0-7633-4378-8b33-52719aa23078.mp4
=> feat: added separate ai section & ai tools #103

CONTRIBUTING.md, src/DB/product.json
I've updated a link of git clone command and added a new resource.
=> New resources abhidadhaniya23

src/DB/product.json
=> Added font awesome to tools

README.md
=> Closes #122

package.json, src/components/footer.jsx, src/styles/footer.css
**Closes #125** 
Hover color:
Icons:
=> Changed hover color and added icons for GitHub and Twitter

src/DB/product.json
Added 6 New Chrome Extensions.
- Text Blaze
- What Font
- Black box
- Keepa
- Screenity
- Link to Text
=> Issue #132: Added six more useful chrome extensions

src/DB/product.json
Remove some broken links, like Pogo, and Soap2Day.
Fix some links that were half-written, like Pika Style, Code Beautify, and 100L5.
Other links are alright.
=> fix: remove broken links, fix some links

src/DB/product.json
Added Friv.com - a free online gaming portal for small games. Closes #136
=> Closes #136

src/DB/product.json
This website is search engine for PDF files.
closes #135
=> Added PDF drive tool

src/DB/product.json
=> link addition: added scribe  #139

src/DB/product.json
=> link addition: added beatoven #141

src/DB/product.json
=> link addition: added krisp ai #140

src/App.jsx, src/components/header.jsx, src/styles/header.css
Closes #130 
Updated search bar:
=> feat: Added the ability to search by category.

package-lock.json, src/DB/product.json
Added 2 ai website and 1 extension
=> added tome, chatGPT-sidebar and ask-your-pdf

src/DB/product.json, src/components/Icons.jsx, src/components/card.jsx
I remove the svg, button, and merge the section to useful tools.
=> merge 'Tweet to Image' to 'Useful tools' and remove the 'Tweet To Image' button

src/DB/product.json
Hello Jason I have added Friday.app under useful tools, Ideasai under AI and Merlin under  extensions.
I have also shorten the links which is more good
=> Added the friday.app , Ideasai and Merlin

src/DB/product.json
Hello @JasonDsouza212 I have added the Emojipedia under tools category
=> Emojipedia

src/DB/product.json
I have added the Mocha.js , chai.js and chai matchers in the products.json file
@JasonDsouza212
=> Addition of Products in the prducts.json file

src/DB/product.json
I have added Open-Graph in Products.json file under tool category.. @JasonDsouza212 
issue no - #183
=> Added the Open-Graph in the tools category

src/components/footer.jsx
added github and twitter account links of Jason Dsouza on footer
=> add: github & twitter links

src/DB/product.json
Fixes Issue #192 Added Undraw as Tool :)
=> Added undraw as Tool

src/DB/product.json
**Updating product.json**
There is an AI tool whch make present from ideas that you entered as text.
=> Add Gamma AI

README.md
=> docs: changed the image #222

src/DB/product.json
=> Added new tool 🥳(Awesome Screen Recorder and Capture)

src/DB/product.json
These are handy tools for developers to make everyday activities easier
=> Update product.json : Added IT Tools in the tools category

src/styles/header.css
fixes #244
Affected files:
- _src/styles/header.css_
=> feat: cursor set to pointer on hover

src/DB/product.json
Added the product "daily.dev" website in the category tools, provided the link for the website, added a logo image for it, and offered a simple description.
=> Updated product.json and added the website "daily.dev" 

src/components/card.jsx, src/styles/card.css
Fixes Issue #240 .
Fixes Issue #252 .
=> Fixed the button click issue.

src/DB/product.json
=> Added naturalreaders to tools

src/styles/header.css, src/styles/index.css
Fixed the responsiveness issue in mobile.
Before:
After:
This solves issue #255
=> Fix: Responsiveness issue in mobile

src/DB/product.json, src/DB/showwcase-site
=> Add Showwcase website

src/components/card.jsx, src/styles/card.css
Solves #258 
Hey , Have fixed the text overlapping into the icon have provided SS below 
Have tested it on all screen and on all other cards it was no longer overlapping now 
Plz review it 
Thanks
=> Fix: text overlapping onto icon

src/DB/product.json
Made the required changes in the product.json (add PDF24 there)
#270
=> Add PDF24 to tools

src/DB/product.json
Added linkedin. LinkedIn is a business and employment-focused social media platform that works through websites and mobile apps. It launched on May 5, 2003. It is now owned by Microsoft
=> Added linkedin

src/DB/product.json
Issue #294
This PR adds the Fatkun browser extension to the project, which helps users to download all pictures on the page with one click, it's smart scripts automatically filter the pictures users need, such as e-commerce pictures, automatically filter the main picture, SKU picture, and detailed picture, and display them in categories.
=> Added the Fatkun browser extension [GSSoc'23]

src/DB/product.json
Fixed Issue: #287
All the broken images in product.json are fixed with high-quality images from trusted sources to provide a great user experience.
Thank You
=> Fixed all the Broken Images with high quality images

src/DB/product.json
Fixed issue: #287
Hey, earlier PR was made to fix all the broken images but still, there were new broken images that were the result of expired links and I have repaired them again.
I hope this will solve the issue now.
Thank You.
=> [Fixed]: Broken Images Bug

src/DB/product.json
=> Added piped and formatted product.json

src/DB/product.json
I just added an user testing which will help user to get feedback
=> added an usertesting site

src/components/aboutnav.jsx, src/components/header.jsx
Added a separate tab for the About page in the navbar which was requested by others earlier. I have added an About tab in the navbar without any style issues, this about tab will be shown on both the Home page and the Bookmark page (No need to be shown on the About page itself). And as there is a separate tab for About now the site logo points to the Home page.
I hope this new addition will add more convenience to the users.
Thank You...
=> Added separate About tab in navbar.

src/components/card.jsx
Issue no: #321 
Description: remove an anchor tag which was  an main issue of after clicking a bookmark it scolls back to top and also added a font syle to delete button..
=> Resolved a bug

src/styles/about.css, src/styles/card.css, src/styles/header.css, src/styles/index.css
I have added some hover effects in the cards and navbar section
Made the scrollbar look better in contrast with the website theme
Fixed a bug in the learn more button on the About page
Before:
In this the learn more button is overlapping with other content and scrollbar does not look good
After:
Here the issue in the "learn more" button is fixed as well as the scrollbar looks nice.
i have also added hover effects in the cards and navbar which can't be shown through photos.
Please mark this under GSSOC'23.
=> I have added hover effect in card buttons and navbar links,made the scrollbar beautiful and also fixed a bug in the About section

src/DB/product.json
four tool that has been duplicated in database (fatkun, reduce image, css shadow, sd moviepont ) has romved sucessfully
=> duplicated tools are removed from database

src/App.jsx, src/components/Community.jsx, src/components/header.jsx, src/components/team.jsx, src/styles/community.css, src/styles/contribution.css, src/styles/index.css
Add a contribution page.
Issue No: #285
**Description:**
I maintained the black and white theme and only hovering on the image will show color and clicking on it will take you to their github page.
**Contribution Page Screenshot.**
=> feat: add contribution page

src/styles/header.css
=> style: style active link in navbar

src/DB/product.json
Solved Issue: #383 
Added Material UI in the list
=> Added Material UI in the list

src/styles/header.css
=> change font properties of header links

src/DB/product.json
closes #396 
- Add a new `movie` tool in the Database
=> [Feat]: Add `Movie` tool in DB

pnpm-lock.yaml, src/DB/product.json
=> Smallpdf added as a new tool

src/styles/index.css
Fixed the navbar responsiveness.
=> Navbar Fix

src/DB/product.json
* Added Unlighthouse and Regexr in tools category
Issue number: #408
=> [Feat]: added new tools

src/DB/product.json, src/components/Data/categories.jsx
@johnsonAyo , I have added UI/UX Category with 9 Free Tools with Bitly url
=> Added UI/UX Tools Category with all required things

src/components/Card/ListView.jsx, src/styles/ListView.css
Styles fixes for Issue - [#431](https://github.com/JasonDsouza212/free-hit/issues/431)
=> styles fixes and accordion changed from multiple to single for issue #431

src/App.jsx
I tried to implement #394  using LCS/levenshteinDistance method. The method is added retaining the existing filtering feature , and fuzzy search is added only to the product name.
Resolved the conflicts #424
=> resolve conflicts - Fuzzy Search

src/components/header.jsx, src/styles/header.css, src/styles/index.css
Header section is now responsive for all devices.
Closes #413
=> IMPROVED HEADER 

src/DB/product.json
zarla , animoto and zety these are added
closes issue number #467
=> Added 3 more products to list

src/components/Card/GridView.jsx, src/components/Card/ListView.jsx
=> Fixed the redirect bug on clicking bookmark button

src/DB/product.json
=> Removed the duplicate tool

src/pages/Bookmarks.jsx, src/pages/Home.jsx, src/utils/check_filters.js, src/utils/data/filters.js
=> fix: redirect to not found page if filter is invalid

src/DB/product.json
Hello Sir,
I, having issue number #480 has added one tool "Novoresume" to it.
Kindly review and merge it.
Regards,
Jyoti Rani
=> New tool added 

src/components/Footer.jsx, src/styles/Footer.css
=> Fixed issue #500

src/pages/Home.jsx
=> Fixed issue #502

src/components/Card/GridView.jsx, src/styles/Home.css
Closes #501 
I updated the styling of cards in grid view. Enhancements:
- Left alignment of content which increases readability of content.
- Handled cards with more content which was breaking UI earlier
- Removed some redundant CSS.
=> Fixed issue #501

pnpm-lock.yaml, src/DB/product.json
Closes #495  and #496 
New Tools FontSpace and Freepik added.
- [x ] I have included comments in areas that may be difficult to understand.
- [x ] My changes have not introduced any new warnings.
=> closes Issue  #495 #496 New Tools FontSpace and Freepik added GSSOC 2k23

pnpm-lock.yaml, src/components/Navbar.jsx, src/styles/header.css
I have been assigned to improve the visiblity of About sidebar in issue #494 
Before
After
=> Improved visiblilty in sidebar of about

src/components/Card/ListView.jsx
=> Changed a bug in the list view

src/styles/Home.css
Closes #452 
I have aligned the cards properly.
=> cards-aligned-properly

src/DB/product.json
🛠️Fix to issue #451 
✅Added and Updated the old Leetcode extension with the new Extension LeetSync
=> fix leetcode extension

src/styles/header.css
=> fixes: about page sidebar font-style

pnpm-lock.yaml, src/DB/product.json
This PR is created in reference to Issue No.: #335 
Also this PR is a continuation of a closed PR.: #450, which was accidentally closed as  the fork got deleted by me
=> [Feat] : Adding a UI tool

src/components/Card/GridView.jsx, src/components/Card/ListView.jsx, src/components/Footer.jsx, src/components/Navbar.jsx, src/pages/About.jsx, src/pages/Bookmarks.jsx, src/pages/Home.jsx
Closes #537 
Added alt attribute to all img tags which improves SEO and user experience.
=> Alt attributes added in img tags

src/DB/product.json
=> Add Trello and Mixkit to the tools category

pnpm-lock.yaml, src/DB/product.json
Closes #560 
Added a new tool (StackBlitz)
=> Adding new tool

pnpm-lock.yaml, src/DB/product.json
=> Correct Misspelling of Tool Name

src/App.jsx, src/styles/Team.css, src/styles/index.css
=> background color bug fixed

src/utils/data/filters.js
Closes  #552
Now when we click upon the frontend tools category we get the tools, earlier we were directed to a blank page.
=> added the web category inside filters.js

src/DB/product.json
=> fixes: remove duplicates from products.json

src/DB/product.json
#601 
Closes #601 
- Roadmap.sh is a community effort to create roadmaps, guides and other educational content to help guide developers in picking up the path and guide their learnings.
- Just added required info about roadmap.sh in the tools category of products.json
=> Siddarthdayala #601

src/App.jsx, src/components/Card/GridView.jsx, src/components/Card/ListView.jsx, src/components/Navbar.jsx, src/pages/Bookmarks.jsx, src/pages/Home.jsx
I've removed the search feature from app component.
Also, I've changed the search feature to use query params and we will be adding `?q='search-value'` in the url.
Hence we don't have to use `useState` and `useEffect` hooks any more for searching and filtering purposes.
Also, this has fixed some of the bugs which were there in the search functionality.
Fixes #460
=> Refactor: use Search params for searching and clean the code in app component

src/pages/Bookmarks.jsx, src/pages/Home.jsx
=> fixes: search suggestions bug

src/DB/product.json
#609 
Closes #609 
- Ant Design is one of the most popular Frontend UI libraries to provide user-friendly React components to make development look clean, run faster and efficient
- Just added info about Ant Design in tools category of products.json
=> Siddarthdayala #609

src/components/Pagination.jsx, src/pages/Home.jsx, src/styles/Home.css, src/styles/Pagination.css
=> enhance: add pagination options at top

src/DB/product.json
Closes #620 
Added Replit website 
reenshots
=> Replit website added

pnpm-lock.yaml, src/DB/product.json
Closes #336
As previously mentioned in issue, the link provided in the project for the DownloadHub Website is not functioning correctly. After conducting a thorough search for alternative URLs, I have determined that none of them are reliable and functional. Therefore, I suggest considering the removal of this website, as there are numerous other sources available for accessing movies.
=> fix: Download Hub Website URL

src/DB/product.json
Closes #631
Add a
{
"productName": "w3schools",
"category": "coding",
"image": "https://bit.ly/3JiwHFx",
"link": "https://w3schools.com/",
"description": "Tutorials on web development, programming languages, and other related technologies"
},  to site w3schools is website where you get different programming language tutorials.
=>  add w3schools 

src/pages/Community.jsx
=> feat: add loader on contributors page

src/DB/product.json
Tutorials Point website provides the best learning material on technical and non-technical subjects
=> Adding new Ed Tech Website

src/DB/product.json
Closes #623 
I have added the new website 1337x which enables the users to surf all new released movies, series, books, anime, etc.
=> added new website 

src/DB/product.json
Closes #499 
Added CSS battle website to free-hit
=> Adding CSS battle website

src/DB/product.json
Closes #603 
- freeCodeCamp is a non-profit organization that consists of an interactive learning web platform, an online community forum, chat rooms, online publications, and local organizations that intend to make learning web development accessible to anyone.
- Added info about freeCodeCamp in tools category of products.json
=> Balasarvan12 #603

src/DB/product.json
Closes #622 
I added [HyperWrite](https://www.hyperwriteai.com/) to the AI category.
=> Add HyperWrite to the AI category

src/DB/product.json
Closes #626
I have fixed the Piped site which belongs to movies
=> I have fixed the bug

src/pages/NotFound.jsx
=> Image Imported in not found page

src/DB/product.json
Closes #607 
Added js challenger website to the database
{
productName: "jschallenger",
category: "Coding",
image: "https://tinyurl.com/5n6vbc7f",
link: "https://www.jschallenger.com/",
description: "Learn Javascript online by solving coding exercises."
}
=> Added jschallenger website in free-hit

src/DB/product.json
Closes #663 
Netlify provides offers a development platform that includes build, deploy, and serverless backend services freely.
=> Add the completely free website hosting service by Parmesh Bhatt

src/styles/index.css
Closes #588 
I have fixed responsiveness for small devices , now it will be working fine on almost every small device.
=> responsiveness fixed for small devices

src/DB/product.json
Closes #647 
Slides AI
Slides AI is an AI-powered tool that assists in creating and enhancing presentation slides. It leverages artificial intelligence technology to automate certain tasks and provide intelligent suggestions to improve the overall design and content of slides.
AutoDraw
AutoDraw is an AI-powered tool developed by Google that assists users in creating drawings and sketches by providing intelligent suggestions and predictions. It aims to simplify the drawing process, especially for individuals who may not have strong artistic skills or struggle to translate their ideas into visual representations.
Uizard
Uizard is an AI-powered UI design tool that helps you design wireframes, mockups, and prototypes in minutes. It has a number of features that make it ideal for both …
=> Added some AI tools like Slidesai, Uizard, Autodraw, Starrytars

public/robots.txt, public/sitemap.xml
Closes #582 
added a sitemap.xml and a robots.txt file to the website to improve the SEO performance of the site.
=> added a sitemap to the website

src/DB/product.json
#695 
Closes #695
- Chakra UI is a popular React component library that provides a set of accessible and customizable UI components. 
- It offers a wide range of pre-designed components and utilities, allowing developers to build responsive and visually appealing user interfaces quickly. 
- With its flexible and composable API, Chakra UI simplifies the process of creating modern web applications with a focus on accessibility and user experience.
- Added info about Chakra UI in tools category of products.json
=> BALASARVAN12-#695

src/DB/product.json
Closes #689 
Otter AI
Otter AI is a voice-to-text transcription software that uses artificial intelligence to create real-time transcriptions of audio and video recordings. It can be used for taking notes at meetings and interviews, transcribing lectures and podcasts, capturing ideas and thoughts etc.
Runway AI
Runway AI is a cloud-based video editing and effects platform that uses artificial intelligence to automate many of the tedious and time-consuming aspects of video editing.
Otter AI
Runway AI
=> Added Otter and Runway AI tool

src/DB/product.json
=> adding google bard

src/components/Navbar.jsx, src/components/Sidebar.jsx
=> refactor: add sidebar component

src/DB/product.json
Closes #701
I had made a pr before with indentation and conflicts and changes made the code messy ,so I closed the prev. pr and created new one. Hope now things are ok.
- [x ] My changes have not introduced any new warnings.
=> Added fireship tailwind tricks link  issue-701

src/App.jsx, src/components/Layout.jsx, src/components/Navbar.jsx
=> refactor: use layout component

src/styles/header.css
Closes #628 
- Fixed the issue of options moving on hovering
- Enhanced styling of the sidebar
- Removed some redundant CSS
| Before | After |
| -- | -- |
| ![image](https://github.com/JasonDsouza212/free-hit/assets/57594891/ccb747d6-7e20-437a-a12c-75fe14c7c003) | ![image](https://github.com/JasonDsouza212/free-hit/assets/57594891/ff7e9c6a-194c-4c63-9875-146e49b4fcbd) |
=> Fixed #628, enhanced styling

src/components/Sidebar.jsx
=> fixes: hide the filters on community page

src/DB/product.json
Closes #676
Google Talk to Books was a unique website that utilized artificial intelligence to provide users with direct access to a vast library of books. Users could ask questions or input phrases, and the AI would scan through thousands of books to find relevant passages and provide instant answers or insights based on the text. It was a valuable resource for researchers, students, and anyone seeking information from a wide range of literary sources.
- [] I have included comments in areas that may be difficult to understand.
=> talk to books.

src/DB/product.json
Closes #690
Class Central is a website that lists online courses from top universities and providers.
=> Adding class central.

src/DB/product.json
Closes #747 
Addition of Frontend Mentor. A platform providing challenges to frontend developers
=> Added frontend mentor website #747

src/DB/product.json
Closes #726 
AI Resume Builder helps the developer to create their resume freely and efficiently and the developer doesn't have to worry about it.
=> Added the AI resume builder by Parmesh Bhatt

.github/workflows/linting.yml
* Closes #745 
Added the prettier linter to ensure proper and uniform linting of the codebase.
After every push, pull request the linting checks will run ensuring standard code formatting.
=> Added the Linter Workflow

.github/workflows/close_old_issues.yml
* Closes #751 
Added a workflow which will automatically close if an issue if it is not active for 20 days.
=> Automatically close old issues 

pnpm-lock.yaml, src/DB/product.json
Closes #742 
Hey, @JasonDsouza212 I have added momentum to extensions. Please review this pr and merge it.
=> Added Momentum to extensions

src/DB/product.json
This PR Closes #729 .
I have added the poised AI link , image in products.json . 
Kindly review it.
Screenshots
Code:
=> Added poised AI related to issue-729

src/DB/product.json
Closes #720 
Text2SQL is used to convert natural language queries into SQL queries. It can be used by data analysts, data scientists, and other professionals who need to write SQL queries.
=> Added Text2SQL AI

src/DB/product.json
=> [Feat]Add a new tool(Pomodoro tool) to increase user productivity[gssoc'23]

src/DB/product.json
Closes #698 
Add Read Aloud extension
=> Add Read Aloud extension

src/DB/product.json
Closes #739 
Added USACO website
=> Added usaco website

src/DB/product.json
Closes #793 
Evernote Web Clipper is a browser extension that lets you save interesting things you find on the web directly to your Evernote account.
=> Added Evernote extension

src/pages/Bookmarks.jsx
=> feat: add list and grid view on bookmarks page

src/DB/product.json
Closes #693 
Add new website: Walkccc
=> add Walkccc website

src/DB/product.json
Closes #694 
Add new tool for developers: W3resource
=> add W3resource

src/DB/product.json
Closes #697 
Add tool: Eventbrite
=> Add new website Eventbrite for hackathons update

src/DB/product.json
Closes #784 
javascript.info is a website that provides comprehensive tutorials and references on the JavaScript programming language. It is a great resource for learning JavaScript, whether you are a beginner or an experienced developer.
=> Added Javascript.info

src/DB/product.json
Closes #821 
Added foundit.in in remote jobs section.
- [x ] My code adheres to the established style guidelines of the project.
- [x ] I have included comments in areas that may be difficult to understand.
- [x ] My changes have not introduced any new warnings.
=> Added foundit.in [Gssoc'23)

src/DB/product.json
Closes #741 
Hey, @JasonDsouza212 I have added scaler to coding platforms. Please review my pr and merge it. Thank you!
=> Added scaler to coding

src/DB/product.json
Closes #824
Free Software for Effortlessly Manage All Your Passwords and Logins.
=> Added Bitwarden

src/DB/product.json
Closes #757  
Added vegamovies website
=> added vegamovies website

pnpm-lock.yaml, src/DB/product.json
Closes #837 
Added few new tools and api to the project
=> Added new tools

src/DB/product.json
Closes #820 
Just changed the product.json
=> Added GSAP-GreenStock Website

src/DB/product.json
Closes #858 
Added website for KhanAcademy which is an e-learning website
=> Added khanAcademy

src/DB/product.json
Closes #921 
Hey @JasonDsouza212, just wanted to give you a heads-up that I've added a new tool called Imgur to your code. Could you please review and merge this pull request? Thanks a bunch!
=>  Add new tool: Imgur (Issue #921)

src/DB/product.json
Closes #955 
Added 3 free tools, one is related to tools and another 2 is related to movies section
- [✔️] My code adheres to the established style guidelines of the project.
- [✔️] I have included comments in areas that may be difficult to understand.
- [✔️] My changes have not introduced any new warnings.
- [✔️] I have conducted a self-review of my code.
=> addition of sejda, hdtoday, myflixer

src/DB/product.json
Closes #961 
Added pikashows under movies and series along with that added coding ninjas under coding category.
=> Added resources issue#961

src/DB/product.json
Closes #932 
Added cryptozombies website to free-hit
{
"productName": "cryptozombies",
"category": "web",
"image": "https://tinyurl.com/2uf3jrk5",
"link": "https://cryptozombies.io/",
"description": " Learn Solidity and Ethereum DApp development."
}
=> Added cryptozombies website to free-hit

src/DB/product.json
Closes #857 
Offers high quality Web3 courses.
- [  ] I have included comments in areas that may be difficult to understand.
=> Added BitDegree

src/DB/product.json
Closes #825 
VLC is a free and open source cross-platform multimedia player and framework that plays most multimedia files as well as DVDs, Audio CDs, VCDs, and various streaming protocols.
=> VLC media Player Added

pnpm-lock.yaml, src/DB/product.json
Closes #754
I have added devfolio,hackclub,mlh,devpost and unstop to coding tool for the ongoing hackathons
=> I have added devfolio,hackclub,mlh,devpost and unstop to coding in the coding tool

src/DB/product.json
Closes #924 
Added the Spline AI in products.json file
=> Added Spline AI related to issue-924

src/DB/product.json
Closes #967 
- Added a new Frontend Tool named `Color Leap`
- It can generate awesome color palattes through the era with our selection on the site, it comes up with best curated colors which we can use for our site to make a good looking site.
=> [CHORE]: ADD COLOR LEAP FRONTEND TOOL ✨

src/DB/product.json
Closes #969 
- This PR is about adding `Haikei` a generator application which can generate Blob, Wave, Blurry Gradients, Circle Scatter, Blob Scene, Layered Waves, etc.
- This tool is one of the best among free resources because it saves lot's of time for developers to generate best vectors/svgs.
=> [CHORE]: ADD HAIKEI FRONTEND TOOL ✨

src/DB/product.json
Closes #863 
I have added freelance tool by which individual can earn by becoming freelancer.
=> Freelance useful tool added

.github/workflows/author-assign.yml
=> ci: Create author-assign.yml #997

src/components/Sidebar.jsx, src/styles/header.css
=> Close the sidebar once filter is selected

.github/pr-title-checker-config.json, .github/workflows/pr-title-checker.yml
=> feat(ci): PR title checker added #999

CONTRIBUTING.md, README.md
=> docs: added new contributing guide  #1032

src/DB/product.json
Closes #920 
Added website for sejda, a pdf editing tool.
=> chore:  added sejda #920

src/DB/product.json
Add:Added AI CodeGpt website #766 
Closes #766 
- CodeGPT is a powerful coding assistance tool based on OpenAI's GPT-3.5 architecture.
- CodeGPT provides a range of functionalities that assist developers in various aspects of coding, including code completion, code explanations, code improvement suggestions, and code creation.
- Added info about CodeGPT in ai category of products.json
=> chore: added CodeGpt 

src/DB/product.json
Closes #952 
Honey is a browser extension that automatically finds and applies coupon codes to save you money while shopping online. It also tracks price history and offers a cashback program.
=> chore: added honey extension

src/DB/product.json
Closes #1146
Need to add new and free latest AI tools so that Website should be more useful and sustainable to the visitors .
https://ibb.co/Xs2PNpS
https://ibb.co/JQXYdcZ
https://ibb.co/S7fprJc
https://ibb.co/nRdrH3N
https://ibb.co/d7GbThX
=> feat: Added Latest Ai Tools

src/DB/product.json
Closes #889 
Added freedom.to(productivity website)
- [x ] My code adheres to the established style guidelines of the project.
- [x ] I have included comments in areas that may be difficult to understand.
=> chore: Freedom

src/DB/product.json
Closes #1144 
Add Glassdoor - Platform to search millions of jobs and get the inside scoop on companies with employee reviews, personalised salary tools, and more.
=> feat: Glassdoor

src/DB/product.json
Closes #872 
I have added a Opus Clip AI tool that repurposes long videos into shorts.
=> chore: Added Opus clip #872

src/DB/product.json
Closes #871 
I have added a new AI tool where user can use this tool to change their own voice into ai voice.
=> chore: Added Lovo #871

src/DB/product.json
Closes #870 
I have added a 10web.io website which builds a website within few minutes using ai.
=> chore: Added 10web.io #870

src/DB/product.json
Closes #869 
I have added a iNeuron website where students can learn and do remote Internships.
=> chore:  Added iNeuron #869

src/DB/product.json
Closes #851 
I have added the resume builder tool - Enhancecv.
=> chore: Added Enhancecv #851

src/DB/product.json
Closes #1108 
- Gradescope
- Ivy ChatBot
- Cognii
- Dragon Education
- Knowji
- Plaito
- Century AI Tools
=> chore: added AI websites for Education #1108

src/DB/product.json
Closes #864 
I have added the Gotranscript tool in db in tools category.
=> chore: Added GoTranscript #864

src/DB/product.json
Closes #865
I have added klap which turn youtube videos into 10x reels, shorts.
=> chore: Added Klap #865

src/DB/product.json
Closes #1019 
- This PR is about adding Handz a 3D gestures library to create yummy graphic design. we can use them in whatever we want to - social media posts, landing pages, blogs, newsletters, etc.
- This tool is one of the best among free resources because it saves lot's of time for developers to instead searching for 3d hand vector images
=> chore: add handz frontend tool ✨

src/DB/product.json, src/utils/data/categories.js, src/utils/data/filters.js
Closes #654 
Added a course section in sidebar with required 8 minimum tools.
=> feat: Added course platform in sidebar

src/DB/product.json
Closes #911 
<I have added a gulp extension.
=> chore: Added Gulp #911

src/DB/product.json
Closes #909 
I have added a Stable Diffusion online - Free Ai art generator.
=> chore: Added Stable diffusion #909

src/DB/product.json
#1107 
Closes #1107 
- CSS Challenges is a resource that offers fun and playful ways to practice your CSS skills. You can do that by playing CSS challenges/riddles or by taking quizzes.
- For challenges, you’ll find five different difficulty levels starting from easy, ranging all the way up to insane.
- Added info about CSS Challenges in tools category of products.json
=> chore: added CSS Challenges

src/DB/product.json
=> chore: Added Just Chill

src/DB/product.json
Closes #1020 
- i-top screen recorder application.
- bandicam screen recorder application.
- cam-studio recorder application.
- Filmora application.
- ScreenCast
- Camtasia
- ShareX
=> chore: added Recorders #1020 

CONTRIBUTING.md
Closes #1167 
Added steps on how to create a pull request and mentioned all the naming conventions.
=> docs: Updated CONTRIBUTING.md by adding PR naming template #1167

src/DB/product.json
Closes #938 
- Movieverse
- HD hub4u
- Movie mint
=> chore: added movies websites #938

src/DB/product.json
Closes #937 
- Grid Garden
- Web-Dev
=> chore: added css websites #937 

src/DB/product.json
Closes #1164 
Added the link for docker.
=> chore: added docker #1164

src/DB/product.json
Closes #1154 
I have added a website where all the algorithms related to competitive programming will be accessible to everyone. It is one of the best site for a competitive programmer and used by large number of coders.
=> chore: Algorithm for Competitve Programming

src/DB/product.json
Closes #907 
I have added BlueWillow - free Ai Art Generator.
=> chore: Added Bluewillow #907

src/components/DarkMode.jsx, src/components/Layout.jsx, src/pages/Home.jsx, src/styles/BackToTop.css, src/styles/DarkMode.css, src/styles/Home.css
Closes #1142 
Hey @JasonDsouza212 I have made the dark mode button available on all the pages. I have created a separate component for the dark mode button to make it available globally. I have also changed the icon and styling to make it more user interactive. Please review my pr and merge it. Thank you!
**Before:-**
**After:-**
=> fix: made the dark mode button available on all pages #1142

src/DB/product.json
=> chore: web.dev added issue #960

src/DB/product.json
Closes #1213,  #1208, #1209, #1211, #1212, #1210
I have added new tools and have placed them in their following categories. Added proof of work below.
=> chore: Added Tools

src/DB/product.json
#1243 
Closes #1243
Added JavaScript Minify Developer tool which purpose is to lower the number of bytes required for transferring web pages and resources to other browsers of different users.
Also allows lowering the size of the web pages and scripts files to enhance performance.
=> chore: JavaScript minify added

src/styles/Pagination.css
Closes #1246 
https://github.com/JasonDsouza212/free-hit/assets/119532943/a3000c11-928a-4838-9564-5dcd6b20c56e
- [x ] I have included comments in areas that may be difficult to understand.
=> style: button hover in the title section #1246

src/DB/product.json
#1244 
Closes #1244 
Hippo Video is an all-in-one platform for all your Video Needs. Record amazing videos, edit with our powerful video editor, share across multiple platforms and see how your video is performing.
=> chore: Hippo Video recorder

src/DB/product.json
Closes #927 
- **Update resumake.io Object in product.json File for Building Latex based Pre-Built Resumes.**
- **Don't know this website to Lot Of Users**
=> feat: resumake.io

README.md
#644 
- Please merge this pull request under GsSOC'23 as I am a participant.
- 
-
=> style: Added Gssoc logo for both light and dark mode

src/DB/product.json
Closes #899 
I have added prettier extension which can be integrated to code editors and supports various programming languages.
=> chore: Added Prettier #899

src/DB/product.json
#1283
tool added 
https://vq.pe/
=> style: #1283 tool added

src/DB/product.json
Closes #918 
- **Update Learners Bucket Object in product.json File for Learning Front End web Development Deeper.**
- **This Website has Interview Questions with Each Topic and Latest & Recent and Top Level asked in Top MNC's, startups and Product based Companies.**
- **In last 10 months, this Website exposed so many useful Content for all levels of Candidates. Especially in LinkedIn Website observed about learning activities.**
=> feat: Learners Bucket

src/DB/product.json
I added 4 tools- Slazzer, Remove.bg, AdBlocker Ultimate, Slides Go.
All the tools are free.
This pull request closes issue #1169
Checklist
=> chore: updated product.json file #1169

src/DB/product.json
Closes #1252 
I added a Snapinsta tool which helps in downloading Instagram reels, photos, reels, stories, IGTV's
=> chore: added tool #1252

src/DB/product.json
Closes #919 
- **Update The Odin Project in product.json File for Learning and Starting Career in Web Development Effectively.**
=> feat: Odin Project

src/DB/product.json
=> chore:  added pdfFiller #1184

src/DB/product.json
Closes #914 
- **Added Edabit Website in product.json File for Learn Programming free with Multiple Coding Challenges**
=> feat: Edabit

src/DB/product.json
Closes #1079, #1083
I have added new tools Css dinner and Codepip  
1.
2.
=> chore: Added Tools 

src/DB/product.json
Closes #1289
Replit being Software as a service (SaaS) allows users to create online projects
=> chore: replit Tools Added   

src/DB/product.json
#1307 
Closes #1307 
BlockSite Extension added to DB Successfully.
=> chore: BlockSite Extension added #1307

src/DB/product.json
Closes #1301 
Added leethub a chrome extension
=> chore: Added Leethub

src/DB/product.json
Closes #913 
- **Added Codewell Object in product.json File for Practicing Different Levels of Projects in Frontend Tech Stacks**
=> feat: Codewell

src/styles/index.css
Closes #1220 
I have made the changes in the style section. Along the x-axis I made the overflow hidden and along the y-axis, it will scroll only, which won't allow the whole webpage to move when we are scrolling
- [x ] My code adheres to the established style guidelines of the project.
=> style: #1220 position changed

src/DB/product.json
Closes #1303 
[Goku](https://goku.sx/home)
=> chore: added movies website #1303

extenstion/DB/product.json
Closes #1308 
Added Gitter(Where Developers come to talk)
=> chore: Added Gitter #1308

src/DB/product.json
Added a tool in Uiverse
Closes #1265 
Added required data in DB/product.js
@JasonDsouza212  Kindly merge it or give your feedback
Add GSSOC label too
=> chore: Uiverse #1265

src/DB/product.json
Added a new tool in the courses category name "Simplilearn"
Closes #1267 
1. Added a new tool in DB/product.json
2.Added a new object have relevant data
@JasonDsouza212 Kindly merge or give your feedback.
Add GSSOC label too.
=> chore: Simplilearn #1267

src/DB/product.json
Added a new tool Name CSS Layout
Closes #1263 
Added required data in DB/product.js
@JasonDsouza212 Kindly merge it or give your feedback 
Add GSSOC label too
=> chore: csslayout #1263

src/DB/product.json
Closes #916 
- **Added BFE.dev Object in product.json for Learn Frontend Skills Practicing Beginners to PRO Level**
=> feat: BFE.dev

src/DB/product.json
Closes #1076 
I have added a new tool flexbox defense
=> chore: Added flexbox defense #1076

src/DB/product.json
Closes #1342
Added Stylized to the AI category.
=> chore: Add Stylized to the AI category

src/DB/product.json
Closes #883 
- **Added Instahyre Object in product.json File for Searching Remote and Startup Jobs with Zero Hassling**
=> feat: Instahyre

src/DB/product.json
The "Codementor"  Website for Learning and Building JavaScript Projects was not present in the database among many other resources.
Closes #904 
Added the required metadata for the mentioned website in the product.json file.
Added the following image as requested "image": "https://user-images.githubusercontent.com/84512164/249226971-111a6f09-4c8e-4921-a9f6-4aacdadf1f45.jpg"
along with the link: https://www.codementor.io/projects
and other metadata including description and category (which seems to fall under 'coding' section)
=> chore: Codementor #904 

src/DB/product.json
Closes #1337 
Added Hi tv under movies category
=> chore: HiTv #1337

src/DB/product.json
ADDED a new tool NPTEL
Closes #1266 
Added required data in DB/product.js
@JasonDsouza212 Kindly merge it or give your feedback
Add GSSOC label too
=> chore: NPTEL #1266

src/DB/product.json
Closes #915 
-  **Added Coding Game Object in product.json File for Learning and Practicing Coding Skills with Real Time Exercises**
=> feat: CodinGame

src/DB/product.json
Closes #1361
This pull request adds the Library Genesis tool to the project. Library Genesis provides access to a wide range of books, articles, and scientific papers, enhancing the resources available to users. This contribution aims to improve the functionality and usefulness of the application.
=> feat: Add Library Genesis tool

extenstion/DB/product.json
=> fix: #1310

src/DB/product.json
Closes #1354 
Corrected the title for the resource as was mentioned by @ERHolguin
=> fix: fixing a typo #1354 

extenstion/DB/product.json, src/DB/product.json
Closes  #1399
I have fixed the Broken Links of Moviesmod Website.
- [ x] I have updated the broken-links.
=> fix: broken-links Moviesmod website

src/DB/product.json
Closes #903 
- **Added Scrimba in product.json File for Learning Frontend Development in various Technologies**
=> feat: Scrimba

CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md
Closes #1339 
Changes mentioned in the issue made.
=> fix: changes to docs

README.md
Closes #1343 
Added the MIT License badge and changed the license section
=> feat: Added the MIT License badge and changed the license section

src/styles/header.css
Bug fix for search input text issue #1402
=> feat: bug fix for issue #1402

src/App.jsx
Closes #1358 
I just made a change in `darkMode` state, that if it couldn't find the `darkMode` in local storage then, check if the device's theme mode is **dark** if yes then make `darkMode` true else false
=> fix: Dark mode according to device's setting initially

src/App.jsx, src/components/Navbar.jsx
Closes #685 
what is deboncing 
Debouncing in JavaScript is a practice used to improve browser performance. There might be some functionality in a web page that requires time-consuming computations. If such a method is invoked frequently, it might greatly affect the performance of the browser, as JavaScript is a single-threaded language. 
**check this video for better understanding -** 
https://youtu.be/qHKHASOuuFA
=> feat: search box debouncing feature

src/DB/product.json
Closes #1392 
I added Numerous.ai to the AI category.
=> chore: Add Numerous.ai to the AI category

src/DB/product.json
Closes #1340 
You can read any manga/manhwa or any other comics for free that too in original quality.
=> chore: added comic website #1340

src/components/Footer.jsx
Closes #1205
added About us page to the footer logo. 
On clicking the footer logo it will navigate to the about us page
please review it!
=> chore: adding link to the footer logo

src/styles/Home.css
Closes #1276 
I have changed the color of the svg icon , now it will have black color in light mode and white color in dark mode
=> chore: color of SVG icon changed

src/DB/product.json
Closes #1377 
- **Added Cisco Networking Academy in product.json File for Learning JavaScript for Free.**
- **This Certification gives More Weightage to Personal Portfolio**
=> feat: Cisco Networking Academy

src/DB/product.json
Closes #1376 
- **Added Scaler Topics Website in product.json File for Learning Coding Related Courses, Contests and Other Activities provided at One Place**
=> feat: Scaler Topics

README.md
Closes #1439 
Updated some docs
=> docs: updated some docs #1439

src/DB/product.json
Closes #1431 
Added Chegg Internships
=> chore: Added Chegg Internships #1431

src/DB/product.json
Closes #1375 
- **Added Great Learning Academy in product.json File for Learning Different Courses in Current Demands like Software Development, Other Programming Languages**
=> feat: Great Learning

extenstion/DB/product.json
Closes #1462 
Added new tool to watch anime for free in sub/dub in movies category
=> chore: added aniWatch website #1462 

src/styles/BackToTop.css
Closes #1287 
The earlier scroll-up button was clearly not visible as the background color was also similar, hence changed the color to increase its visibility.
- [' '] I have included comments in areas that may be difficult to understand.
=> style: Added visibility to scrollup button #1287

src/DB/product.json
Closes #1410 
[WordPress](https://wordpress.com/)
=> chore: added wordpress website #1410

src/DB/product.json
Closes #1409 
Vercel
Heroku
DreamHost
BlueHost
=> chore: added deploying website #1409

index.html
Closes #1437 
- Created a custom image for open graph tags.
- Added the image to the open graph tags.
- Fixed the head tag by pairing it with the closing tag.
=> feat: open graph image add

src/components/Card/GridView.jsx, src/components/Card/ListView.jsx
Capitalization of first letter #1330
Closes #1330
I have make all products name first letter capital in grid view as well as list view in Home Page
=> fix: Capitalization of first letter #1330

index.html
Closes #1437 
Update the open graph image with the new image with the updated logo, which I couldn't update in the previous PR.
=> fix: update open graph image

src/DB/product.json
Added a new tool Name Particles js
Closes #1264 
Added required data in DB/product.js
@JasonDsouza212 Kindly merge it or give your feedback
Add GSSOC label too.
=> chore: particles js #1264

src/DB/product.json
Closes #1427 
- **Added Dev Practical Details in product.json File for Learning Frontend Web Development Free**
=> feat: Dev Practical

src/styles/Footer.css
Closes #1451 
Updated Github Logo Hover Effect Color
=> fix: Updated Github Logo Hover Effect Color

src/DB/product.json
Closes #1088 
Proxy server tool for managing and routing network traffic with enhanced security features
=> chore: Added Envy Proxy

src/DB/product.json
Closes [#issue_number](https://github.com/JasonDsouza212/free-hit/issues/1369)
Add ortus chrome extension
- [X ] My code adheres to the established style guidelines of the project.
- [ X] I have included comments in areas that may be difficult to understand.
- [ X] My changes have not introduced any new warnings.
- [X ] I have conducted a self-review of my code.
=> feat: Update_product.json

src/DB/product.json, src/utils/data/categories.js, src/utils/data/filters.js
Closes #1227 
8 tools under category "image generation added". Now I will also add the category in filters.
=> chore: Tools for image generation added #1227

src/components/Navbar.jsx
Closes #1455
I am proposing an enhancement to the sidebar functionality, which will automatically close the sidebar when users opens the sidebar and start scrolling. This improvement aims to create a smoother and more intuitive user experience, making navigation seamless and reducing unnecessary interactions.
- Enhanced Usability: With the sidebar closing automatically during scrolling, the content remains easily accessible and visible at all times. This eliminates the need for users to manually close the sidebar, streamlining their interactions with the website.
https://github.com/JasonDsouza212/free-hit/assets/110842297/eb87bdf3-d90a-43e5-8b22-ca5af3cf0fa7
=> feat: Auto-Close Sidebar on Scroll

src/DB/product.json
Closes #1429 
- **Added Practity Details in product.json File Learning Web Development Free**
=> feat: Practity

src/DB/product.json
Closes #885 
- **Added TabnineAI details in product.json file in extensions Category.**
- **It's useful for Writing better code with More Securable**
=> feat: Tabnine AI

src/components/Card/GridView.jsx, src/components/Card/ListView.jsx
Closes #1458 
- Added share feature with Web share API
Video Links:
Microsoft Edge: https://www.loom.com/share/13feeec563d644738b5f81c0e42a750a?sid=ee35aab5-07ef-4510-81a0-8ffaf58a431e
=> fix: added share functionality #1458

src/components/Navbar.jsx
Closes #1474 
I have Capitalized the result so It will reflect all categories.
=> fix: Capitalization of search suggestion #1474

src/DB/product.json
=> chore: Add Free3Dicon to the tools category.

src/DB/product.json
Closes #1509 
chore : Added 3 VSCode extensions to the extensions category
This PR adds 3 useful VSCode extensions enhancing productivity and optimizing the coding experience. 🚀
Updated their names !!!
=> chore: Added 3 VSCode extensions to the extensions category

src/App.jsx
Reference Error in code #1488
Closes #1488 
I have handle timer in debounce function.
=> fix: Reference error #1488

extenstion/DB/product.json
Closes #1518 
Removed the repeated tool. 
- [] I have included comments in areas that may be difficult to understand.
=> chore: Removed repeated tool uiverse.io

src/styles/ListView.css, src/styles/Pagination.css
Closes #1470 
Added padding similar to grid view to the list view so we can have a uniform design
=> fix: list view (pagination) padding

src/pages/Bookmarks.jsx
Closes #1466
- This PR is about fixing the bad contrast color of list item toggle button.
<table border="3">
<tr>
<th>C U R R E N T &nbsp; S T A T E</th>
<th>D E S I R E D &nbsp; S T A T E</th>
</tr>
<tr>
<td>
<table border="1">
<tr>
<th>LIGHT</th>
<th>DARK</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
</td>
<td>
<table border="1">
<tr>
<th>LIGHT</th>
<th>DARK</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
</td>
</tr>
</table>
=> fix: bad contrast color of list item toggle button 🛠

src/DB/product.json
Closes [ #issue_number](https://github.com/JasonDsouza212/free-hit/issues/1416)
It helps find what people are searching for on Amazon, and align your product listings with those terms.
- [ X] My code adheres to the established style guidelines of the project.
- [X ] I have included comments in areas that may be difficult to understand.
- [ X] My changes have not introduced any new warnings.
- [X ] I have conducted a self-review of my code.
=> feat: Update_product.json-1416

src/styles/header.css
Closes #1520 
Added the new css for searchbar.
changes:
=> fix: added the searchbar css #1520

src/DB/product.json, src/utils/data/categories.js, src/utils/data/filters.js
Closes #1511 
Added code to include the category 'API' and added a free api in the DB.
=> feat: Added Category 'API'

src/DB/product.json
Closes [#1418](https://github.com/JasonDsouza212/free-hit/issues/1418)
it helps Get more views on YouTube by researching keywords people are searching for.
- [X ] My code adheres to the established style guidelines of the project.
- [X ] I have included comments in areas that may be difficult to understand.
- [X ] My changes have not introduced any new warnings.
- [X ] I have conducted a self-review of my code.
=> feat: Update_product.json-1418

src/DB/product.json
Closes [#1415](https://github.com/JasonDsouza212/free-hit/issues/1415)
Add broken-link-checker
It helps check your site for broken inbound and outbound links in seconds.
- [X ] My code adheres to the established style guidelines of the project.
- [X ] I have included comments in areas that may be difficult to understand.
- [X ] My changes have not introduced any new warnings.
- [X ] I have conducted a self-review of my code.
=> feat: Update_product.json-1415

src/DB/product.json
#1469 
Closes #1469 
Just added a new learning platform called UpGrad in product,json file
=> chore: added UpGrad 

README.md
Closes #1495 
Added the reason in readme as to why to contribute in open source.
=> docs: Updated main README.md

src/DB/product.json
=> chore: Add Icon-Icons to the tools category.

src/components/Sidebar.jsx, src/styles/header.css
side menu active Tabs issue #1532 fixed
=> fix: side menu active Tabs #1532

src/components/Navbar.jsx
=> refactor: navbar code  #1546

src/components/Navbar.jsx, src/components/Sidebar.jsx
search input empty  issue #1542
on click of side menu input get empty
=> fix: search input empty  issue #1542

README.md
Closes #1510 
Added a socials section and added badges to it.
=> feat: Added a socials section and badges to that section in the readme

src/DB/product.json
Closes #906 
- **Added Frontend PRO Details in product.json File for Learning Frontend Technologies with Different Level of Challenges.**
=> feat: Frontend PRO

src/DB/product.json
Closes #891 
- **Added Sketch Tool for UI/UX Design in product.json File.**
- **This tool is free to use.**
=> feat: Sketch Tool

src/pages/Community.jsx, src/styles/Community.css
Contributor  Search Feature Added #1544 
search:-
when no contributor:-
=> feat: search Feature Added #1544

src/DB/product.json
Closes Issue #1562 
1.  Rebranded Website Name:
Changed the website name from "Zoro.to" to "Aniwatch.to" throughout the site.
2. Updated Website Links:
Replaced all instances of "Zoro.to" with "aniwatch.to" in the website's code and links.
3. Logo and Branding:
Updated the logo from the old "Zoro.to" logo to the new "Aniwatch.to" logo.
Reviewed and potentially updated other branding elements and details to align with the new website name and branding.
=> fix: Fixes#1562 by adding links, logo and changing name

src/pages/NotFound.jsx
=> fix: Updated the class attribute to className in the JSX code #1563

README.md
Closes #1534 
Added the Table of content to the readme.md
=> feat: Added the Table of content to the readme.md

src/DB/product.json
Closes #1571
Added TinyURL url shortener to DB
=> chore: added TinyURL to tools #1571

src/DB/product.json
Closes #1583 
add Rapid Api tool
=> chore: add Rapid API #1583

src/pages/Community.jsx
pagination feature added #1567 
i am showing 18 userProfile after pagination click other 18 userProfile
=> feat: pagination feature added #1567

src/components/Card/GridView.jsx, src/styles/GridView.css, src/styles/Home.css
image issue  #1539 
before :- 
After :- 
we can also increase the height and width as we are giving condition on the basis of image height
=> fix: image issue #1539

src/App.jsx
bookmark #1597 
hii @JasonDsouza212  i have added pls check and merge my pr.
=> feat: bookMark #1597

package.json, pnpm-lock.yaml, src/App.jsx, src/components/Card/GridView.jsx, src/components/Card/ListView.jsx, src/components/Card/ShareModel.jsx, src/main.jsx
Closes #1600 
- Added `react-hot-toast`.
- Replaced `alerts` with `toasts`
=> style: alert replace with toast

src/DB/product.json
=> chore: add summereyes to the ai category #1586

src/DB/product.json
=> chore: add vondy to the ai category #1603

src/pages/Home.jsx
Closes #1607 
Replaced classname of "no-results" to `no-results ${darkMode ? 'dark-mode' : ''}` , which changes the text color according to the theme(dark or light).
=> feat: solved home page search-text visibility err

src/DB/product.json, src/utils/data/categories.js, src/utils/data/filters.js
Adding the mapban.gg for eSports Category.
Closes #1577 
Adding eSports category and adding mapban.gg tool in it.
https://github.com/JasonDsouza212/free-hit/assets/76244494/11187fb5-cadf-4ba9-8b99-1f442efa4c54
=> chore: mapban.gg for eSports category

src/DB/product.json
Closes #1615
I have added whimsical to the free hit ui desgin tools. Whimsical is a collaborative online tool for creating flowcharts, diagrams, wireframes, and other visual content.
=> chore: add whimsical to the ui category #1615

extenstion/DB/product.json
Closes #issue_number
#702 
I have added an extension called I don't care about cookies. 
I know that gssoc is over but kindly merge it without that label. I don't mind.
=> feat: Added I don't care about cookies

src/DB/product.json
No related issue.
Added new tool, typora.
=> feat: new tool typora

src/DB/product.json
Add new product: Carousel Hero #1644
=> feat: add new product Carousel Hero
